services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns --host 0.0.0.0

  zenml:
    image: zenmldocker/zenml-server
    volumes:
      - ./.zen:/root/.zen
      - ./mlruns:/mlflow/mlruns
    environment:
      - ZENML_SERVER_AUTO_ACTIVATE=1
    ports:
      - "8080:8080"
    depends_on:
      - mlflow
    
  api:
    build: ./api
    ports:
      - "8000:80"
    volumes:
      - ./.zen:/root/.zen  
    depends_on:
      - zenml